### ISSUE TITLE
Add event consolidation

### ISSUE THREAD

**Issue by kuon** [aj-foster/phx_copy#2]
Hello,

I use `phx_copy` in my projects and I access the project through a network mount. Long story short, every time I save a file, it generates a dozen of events, which in turn make live reload crazy.

I think this could be solved by delaying copy for a file for a few milliseconds (configurable). So if you get 10 events for a file in rapid succession, only one copy is done.

If you think this is a good idea, I'll make a PR.

**Comment by aj-foster** [comment]
Hi there!

That sounds like a great idea. Just a heads-up, I am away from home this week, so may not get to see any PRs until later. But please feel free to create a PR with what you have in mind.

Thank you!

**Comment by aj-foster** [comment]
Released as [0.1.2](https://hex.pm/packages/phoenix_copy/0.1.2).
